[project]
name = "gitsync"
version = "0.1.0"
description = "Auto git commit with AI-generated messages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.46",
    "openai>=2.16.0",
    "rich>=14.3.2",
]

[project.scripts]
gitsync = "main:main"
